# Generated by Django 4.2.3 on 2023-07-24 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=17)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=30)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.usertype')),
            ],
            options={
                'db_table': 'user_master',
            },
        ),
        migrations.CreateModel(
            name='TrainerDetails',
            fields=[
                ('trainer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
                ('details', models.TextField(max_length=250)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.usermaster')),
            ],
            options={
                'db_table': 'trainer_details',
            },
        ),
    ]
